# Generated by Django 4.2.7 on 2024-10-29 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("staff", "Staff")],
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Student No./Staff No. (5 or 9 digits).",
                        regex="^\\d{5,9}$",
                    )
                ],
            ),
        ),
    ]
