# Generated by Django 4.2.7 on 2024-08-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_category_title_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                decimal_places=2, default="2.99", max_digits=9999999
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default="1.99", max_digits=9999999
            ),
        ),
    ]
