# Generated by Django 4.2.7 on 2024-10-28 08:31

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="staff_price",
            field=models.DecimalField(decimal_places=2, default="2.99", max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="student_price",
            field=models.DecimalField(decimal_places=2, default="1.99", max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(decimal_places=2, default="2.99", max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="pid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=22,
                max_length=30,
                prefix="",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                length=22,
                max_length=30,
                prefix="sku",
                unique=True,
            ),
        ),
    ]
