# Generated by Django 4.2.7 on 2024-10-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_remove_product_price_product_staff_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
