# Generated by Django 5.1.2 on 2024-10-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_cartorder_options_alter_cartorder_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payfast_id",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
