# Generated by Django 5.1.2 on 2024-10-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_cartorderitems_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorderitems",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="qty",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
