# Generated by Django 5.1.2 on 2024-10-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_alter_cartorderitems_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorderitems",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
